apiVersion: v1
kind: Service
metadata:
  name: git-events-eventsource
  namespace: argo-events
spec:
  selector:
    app.kubernetes.io/name: git-events-eventsource
  ports:
    - protocol: TCP
      port: "12000"
      targetPort: "12000"
