apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: git-events
  namespace: argo-events
spec:
  github:
    example-repo:
      owner: vasplustechnologies
      repository: argo-gitops-project
      webhook:
        endpoint: /push
        port: 12000
      events:
        - push
      apiToken:
        secretKeyRef:
          name: github-token-secret
          key: token
