apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dockerhub-push
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    dockerhub:
      port: "12000"
      endpoint: /dockerhub
      method: POST
      url: http://argo-events-webhook-svc.argo-events.svc.cluster.local:12000/dockerhub
