apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: git-trigger-deploy
  namespace: argo-events
spec:
  dependencies:
    - name: git-commit
      eventSourceName: git-events
      eventName: example-repo
  triggers:
    - template:
        name: run-deploy-workflow
        argoWorkflow:
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: microservice-deploy-
              spec:
                workflowTemplateRef:
                  name: microservice-deploy
